/**
 * @license
 * SPDX-License-Identifier: Apache-2.5
 */

import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Coins, 
  User, 
  Calendar, 
  TrendingUp, 
  Award, 
  ChevronDown, 
  Search,
  Sparkles,
  Trophy,
  Activity,
  Layers,
  ArrowUpRight
} from 'lucide-react';

interface ExecutiveIncentiveChartProps {
  authToken: string;
  userRole: string;
  userProfile: any;
}

interface MonthlyData {
  monthKey: string; // e.g. "2026-06"
  monthName: string; // e.g. "Jun 2026"
  baseAmount: number;
  floorBonus: number;
  targetBonus: number;
  teamBonus: number;
  totalIncentive: number;
  salesCount: number;
}

export default function ExecutiveIncentiveChart({ authToken, userRole, userProfile }: ExecutiveIncentiveChartProps) {
  const [incentives, setIncentives] = useState<any[]>([]);
  const [executives, setExecutives] = useState<any[]>([]);
  const [selectedExecId, setSelectedExecId] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(true);
  
  // UI states
  const [hoveredMonth, setHoveredMonth] = useState<string | null>(null);
  const [showSelector, setShowSelector] = useState<boolean>(false);
  const [searchQuery, setSearchQuery] = useState<string>('');

  const monthsName = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

  useEffect(() => {
    const loadInitialData = async () => {
      setLoading(true);
      try {
        // Fetch all incentives relevant to user role permission levels
        const incRes = await fetch('/api/incentives', {
          headers: { 'Authorization': `Bearer ${authToken}` }
        });
        const incData = await incRes.json();
        const incentivesList = Array.isArray(incData) ? incData : [];
        setIncentives(incentivesList);

        // For Admin & Leaders, list all executives to support selecting who to display
        if (userRole === 'Admin' || userRole === 'Sales Team Leader') {
          const execRes = await fetch('/api/executives', {
            headers: { 'Authorization': `Bearer ${authToken}` }
          });
          const execData = await execRes.json();
          const executivesList = Array.isArray(execData) ? execData : [];
          setExecutives(executivesList);

          // Set default selected executive
          if (executivesList.length > 0) {
            // Find executive representing logged-in profile if matching
            const currentAsExec = executivesList.find(e => 
              e.employee_id === userProfile?.employee_id || e.id === userProfile?.id
            );
            if (currentAsExec) {
              setSelectedExecId(currentAsExec.id);
            } else {
              setSelectedExecId(executivesList[0].id);
            }
          }
        } else {
          // For Sales Executive, lock selection to their own entity ID
          const selfExec = incentivesList.find(i => 
            i.employee_id === userProfile?.employee_id || i.executive_id === userProfile?.id
          );
          if (selfExec) {
            setSelectedExecId(selfExec.executive_id);
          } else if (userProfile?.id) {
            setSelectedExecId(userProfile.id);
          }
        }
      } catch (err) {
        console.error("Error loading executive incentive chart data:", err);
      } finally {
        setLoading(false);
      }
    };

    loadInitialData();
  }, [authToken, userRole, userProfile]);

  // Aggregate monthly data for the selected executive
  const getExecutiveMonthlyEarnings = (): MonthlyData[] => {
    if (!selectedExecId) return [];

    // Filter incentives to only those generated by the selected executive
    const execIncentives = incentives.filter(inc => inc.executive_id === selectedExecId);
    
    const aggregates: Record<string, MonthlyData> = {};

    // Prime past 6 months to make sure chart spans logically even if zero earnings
    const now = new Date();
    for (let i = 5; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      const mIdx = d.getMonth();
      const yr = d.getFullYear();
      const monthKey = `${yr}-${String(mIdx + 1).padStart(2, '0')}`;
      aggregates[monthKey] = {
        monthKey,
        monthName: `${monthsName[mIdx]} ${yr}`,
        baseAmount: 0,
        floorBonus: 0,
        targetBonus: 0,
        teamBonus: 0,
        totalIncentive: 0,
        salesCount: 0
      };
    }

    // Accumulate actual record entries
    execIncentives.forEach(inc => {
      // inc.month represents 1-12, inc.year is 4-digit
      const monthKey = `${inc.year}-${String(inc.month).padStart(2, '0')}`;
      const monthName = `${monthsName[inc.month - 1] || 'Month'} ${inc.year}`;
      
      if (!aggregates[monthKey]) {
        aggregates[monthKey] = {
          monthKey,
          monthName,
          baseAmount: 0,
          floorBonus: 0,
          targetBonus: 0,
          teamBonus: 0,
          totalIncentive: 0,
          salesCount: 0
        };
      }

      aggregates[monthKey].baseAmount += Number(inc.base_incentive || 0);
      aggregates[monthKey].floorBonus += Number(inc.floor_bonus || 0);
      aggregates[monthKey].targetBonus += Number(inc.target_bonus || 0);
      aggregates[monthKey].teamBonus += Number(inc.team_bonus || 0);
      aggregates[monthKey].totalIncentive += Number(inc.total_incentive || 0);
      aggregates[monthKey].salesCount += 1;
    });

    // Convert map to calendar sorted array
    return Object.values(aggregates).sort((a, b) => a.monthKey.localeCompare(b.monthKey));
  };

  const monthlyChartData = getExecutiveMonthlyEarnings();
  const maxIncentiveVal = Math.max(...monthlyChartData.map(d => d.totalIncentive), 15000);
  const selectedExecName = executives.find(e => e.id === selectedExecId)?.name || userProfile?.name || "Premium Sales Officer";
  const selectedExecIdNo = executives.find(e => e.id === selectedExecId)?.employee_id || userProfile?.employee_id || "N/A";
  const selectedExecTeam = executives.find(e => e.id === selectedExecId)?.team_name || "Development Division";

  const totalExecutiveEarningsSum = monthlyChartData.reduce((sum, item) => sum + item.totalIncentive, 0);
  const totalExecutiveSalesSum = monthlyChartData.reduce((sum, item) => sum + item.salesCount, 0);

  const filteredExecutives = executives.filter(e => 
    String(e.name || '').toLowerCase().includes(searchQuery.toLowerCase()) || 
    String(e.employee_id || '').toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div id="executive-monthly-earnings-card" className="bg-white dark:bg-slate-900 rounded-3xl border border-gray-150 dark:border-slate-800 p-6 space-y-6 shadow-sm relative overflow-hidden transition-all">
      {/* Title & Selector Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-gray-50 dark:border-slate-800/60 pb-5">
        <div className="space-y-1.5">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wider bg-emerald-50 border border-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:border-emerald-900/40 dark:text-emerald-400 font-mono">
              ★ Active Executive Analytics
            </span>
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping" />
          </div>
          <h2 className="text-base font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <Coins className="w-5 h-5 text-emerald-600" /> Monthly Incentive Earnings Bar Chart
          </h2>
          <p className="text-xs text-gray-500 dark:text-slate-400">
            Interactive breakdown of monthly sequence commissions, target achievements, and special floor override rewards.
          </p>
        </div>

        {/* Executive Selector (Admins / Team Leaders) */}
        {(userRole === 'Admin' || userRole === 'Sales Team Leader') && (
          <div className="relative shrink-0">
            <button 
              onClick={() => setShowSelector(!showSelector)}
              className="flex items-center justify-between gap-2 px-4 py-2 border border-gray-200 dark:border-slate-800 rounded-xl bg-gray-50/50 hover:bg-gray-50 dark:bg-slate-800/40 text-xs font-semibold text-gray-700 dark:text-slate-300 shadow-sm cursor-pointer transition-all w-full md:w-64"
            >
              <div className="flex items-center gap-2 truncate">
                <div className="w-5 h-5 rounded-full bg-indigo-50 dark:bg-indigo-950/50 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
                  <User className="w-3 h-3" />
                </div>
                <div className="text-left font-sans truncate">
                  <span className="block text-[8px] text-gray-400 font-mono leading-none">Viewing Officer</span>
                  <span className="truncate block font-bold leading-tight">{selectedExecName}</span>
                </div>
              </div>
              <ChevronDown className={`w-3.5 h-3.5 text-gray-400 transition-transform ${showSelector ? 'rotate-180' : ''}`} />
            </button>

            <AnimatePresence>
              {showSelector && (
                <>
                  <div className="fixed inset-0 z-30" onClick={() => setShowSelector(false)} />
                  <motion.div 
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: 10 }}
                    className="absolute right-0 mt-2 w-full md:w-72 bg-white dark:bg-slate-900 border border-gray-150 dark:border-slate-800 rounded-2xl shadow-xl z-40 overflow-hidden shrink-0 font-sans"
                  >
                    <div className="p-3 border-b border-gray-100 dark:border-slate-800 bg-gray-50/50 dark:bg-slate-850 flex items-center gap-2">
                      <Search className="w-3.5 h-3.5 text-gray-400" />
                      <input
                        type="text"
                        placeholder="Search employee or name..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full text-xs font-semibold bg-transparent border-0 focus:ring-0 p-0 text-gray-700 dark:text-white placeholder-gray-400"
                        autoFocus
                      />
                    </div>
                    <div className="max-h-56 overflow-y-auto divide-y divide-gray-50 dark:divide-slate-800/50 p-1">
                      {filteredExecutives.map(exec => (
                        <button
                          key={exec.id}
                          onClick={() => {
                            setSelectedExecId(exec.id);
                            setShowSelector(false);
                            setSearchQuery('');
                          }}
                          className={`w-full text-left p-2.5 rounded-xl text-xs flex items-center justify-between transition-colors ${
                            selectedExecId === exec.id 
                              ? 'bg-indigo-50/70 dark:bg-indigo-950/30 text-indigo-700 dark:text-indigo-400 font-bold'
                              : 'hover:bg-gray-50 dark:hover:bg-slate-850 text-gray-700 dark:text-slate-350'
                          }`}
                        >
                          <div className="truncate pr-2">
                            <span className="block truncate font-bold">{exec.name}</span>
                            <span className="text-[9px] text-gray-400 font-mono">ID: {exec.employee_id} • {exec.team_name}</span>
                          </div>
                          {selectedExecId === exec.id && <span className="text-xs text-indigo-600">✓</span>}
                        </button>
                      ))}
                      {filteredExecutives.length === 0 && (
                        <div className="text-center py-6 text-xs text-gray-400">No executives matched search.</div>
                      )}
                    </div>
                  </motion.div>
                </>
              )}
            </AnimatePresence>
          </div>
        )}
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center py-16 space-y-3">
          <div className="w-10 h-10 rounded-full border-3 border-emerald-200 border-t-emerald-600 animate-spin" />
          <p className="text-xs font-medium text-gray-400 font-mono">Compiling monthly commissions database...</p>
        </div>
      ) : (
        <div className="grid lg:grid-cols-12 gap-6 items-stretch">
          {/* Main Bar Chart Panel */}
          <div className="lg:col-span-8 bg-gray-50/30 dark:bg-slate-850/10 border border-gray-100 dark:border-slate-800/80 rounded-3xl p-5 flex flex-col justify-between">
            <div className="flex items-center justify-between mb-4">
              <span className="text-[10px] font-extrabold font-mono text-gray-400 dark:text-slate-500 uppercase tracking-widest flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5" /> Chronological Breakdown
              </span>
              <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 dark:bg-emerald-950/30 px-2 py-0.5 rounded-md font-mono">
                Currency BDT (৳)
              </span>
            </div>

            {/* SVG/HTML Bar Chart Container */}
            <div className="h-64 flex items-end justify-between gap-3 sm:gap-4 border-b border-gray-150 dark:border-slate-800/80 pb-3 pt-6 relative select-none">
              {monthlyChartData.map((month) => {
                const heightPercentage = month.totalIncentive > 0 
                  ? `${Math.max((month.totalIncentive / maxIncentiveVal) * 85, 3)}%` 
                  : '3%';
                const isHovered = hoveredMonth === month.monthKey;

                return (
                  <div 
                    key={month.monthKey} 
                    className="flex-1 flex flex-col items-center gap-2 h-full justify-end group cursor-pointer"
                    onMouseEnter={() => setHoveredMonth(month.monthKey)}
                    onMouseLeave={() => setHoveredMonth(null)}
                  >
                    <div className="w-full flex items-end justify-center h-5/6 relative">
                      {/* Stacked Animated Bar */}
                      <div 
                        style={{ height: heightPercentage }} 
                        className={`w-full max-w-[40px] rounded-t-lg transition-all duration-300 relative flex flex-col justify-end overflow-hidden border border-emerald-500/10 ${
                          isHovered 
                            ? 'bg-emerald-600 shadow-md ring-2 ring-emerald-300 dark:ring-emerald-800/30 scale-x-105'
                            : 'bg-gradient-to-t from-emerald-500 to-teal-400 group-hover:from-emerald-500 group-hover:to-teal-500'
                        }`}
                      >
                        {/* Overlay split colors visually of different bonuses */}
                        {month.totalIncentive > 0 && (
                          <div className="absolute inset-0 flex flex-col-reverse pointer-events-none">
                            {/* Base Sequence commission */}
                            <div 
                              style={{ height: `${(month.baseAmount / month.totalIncentive) * 100}%` }} 
                              className="bg-emerald-500/35 border-b border-white/5" 
                            />
                            {/* Floor overrides */}
                            {month.floorBonus > 0 && (
                              <div 
                                style={{ height: `${(month.floorBonus / month.totalIncentive) * 100}%` }} 
                                className="bg-amber-400/40 border-b border-white/5" 
                              />
                            )}
                            {/* Target bonuses */}
                            {month.targetBonus > 0 && (
                              <div 
                                style={{ height: `${(month.targetBonus / month.totalIncentive) * 100}%` }} 
                                className="bg-indigo-400/40 border-b border-white/5" 
                              />
                            )}
                            {/* Team target bonuses */}
                            {month.teamBonus > 0 && (
                              <div 
                                style={{ height: `${(month.teamBonus / month.totalIncentive) * 100}%` }} 
                                className="bg-rose-450 bg-rose-400/40" 
                              />
                            )}
                          </div>
                        )}
                      </div>

                      {/* Tooltip on individual hover */}
                      <AnimatePresence>
                        {isHovered && (
                          <motion.div 
                            initial={{ opacity: 0, y: -10, scale: 0.95 }}
                            animate={{ opacity: 1, y: 0, scale: 1 }}
                            exit={{ opacity: 0, y: -10, scale: 0.95 }}
                            className="absolute -top-24 left-1/2 transform -translate-x-1/2 bg-slate-900 border border-slate-755 text-white text-[10px] font-medium p-2.5 rounded-2xl z-20 shadow-xl whitespace-nowrap space-y-1 block pointer-events-none font-mono"
                          >
                            <p className="font-bold text-gray-300 font-sans border-b border-slate-800 pb-1 flex items-center gap-1">
                              <Calendar className="w-3 h-3 text-indigo-400" /> {month.monthName}
                            </p>
                            <p className="flex justify-between gap-4 font-extrabold text-xs text-emerald-400">
                              <span>Total:</span>
                              <span>{month.totalIncentive.toLocaleString()} BDT</span>
                            </p>
                            <p className="text-[9px] text-gray-400 flex justify-between gap-4">
                              <span>Sales logged:</span>
                              <span className="font-bold text-white">{month.salesCount} Unit(s)</span>
                            </p>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>

                    {/* Month Label */}
                    <span className="text-[10px] font-bold font-mono tracking-wider text-gray-400 dark:text-slate-500 group-hover:text-gray-700 dark:group-hover:text-slate-300 transition-colors">
                      {month.monthName.split(' ')[0]}
                    </span>
                  </div>
                );
              })}
            </div>

            {/* Horizontal Legend Indicator */}
            <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5 text-[10px] font-medium text-gray-500 dark:text-slate-400 justify-center mt-3">
              <span className="flex items-center gap-1.5">
                <div className="w-3 h-3 bg-emerald-500 rounded-sm" /> 
                Commission Base
              </span>
              <span className="flex items-center gap-1.5">
                <div className="w-3 h-3 bg-amber-400 rounded-sm" /> 
                Floor Overrides
              </span>
              <span className="flex items-center gap-1.5">
                <div className="w-3 h-3 bg-indigo-400 rounded-sm" /> 
                Executive Targets
              </span>
              <span className="flex items-center gap-1.5">
                <div className="w-3 h-3 bg-rose-400 rounded-sm" /> 
                Team Incentives
              </span>
            </div>
          </div>

          {/* Side Aggregates & Breakdown Panel */}
          <div className="lg:col-span-4 flex flex-col justify-between gap-4">
            {/* Upper Badge Profile Info */}
            <div className="bg-indigo-50/40 dark:bg-slate-800/20 border border-indigo-100/50 dark:border-indigo-900/10 rounded-3xl p-5 space-y-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-indigo-500 flex items-center justify-center text-white text-sm font-black font-mono shadow-sm relative overflow-hidden">
                  <div className="absolute inset-0 bg-gradient-to-tr from-indigo-600 to-indigo-400 opacity-90" />
                  <span className="relative z-10">
                    {selectedExecName.split(' ').map((n: string) => n[0]).join('').slice(0, 2).toUpperCase()}
                  </span>
                </div>
                <div className="truncate">
                  <h3 className="text-sm font-bold text-gray-900 dark:text-slate-100 truncate">{selectedExecName}</h3>
                  <p className="text-[10px] text-gray-400 font-mono tracking-wider uppercase leading-none mt-0.5">
                    Employee ID: {selectedExecIdNo}
                  </p>
                </div>
              </div>

              {/* Status Pills */}
              <div className="grid grid-cols-2 gap-2 pt-1 font-mono text-[9px] text-center font-bold">
                <div className="bg-white dark:bg-slate-850 p-2 rounded-xl border border-gray-100 dark:border-slate-800/50">
                  <p className="text-gray-400 font-sans uppercase">Total Earned</p>
                  <p className="text-emerald-600 text-xs mt-0.5 truncate">{totalExecutiveEarningsSum.toLocaleString()} BDT</p>
                </div>
                <div className="bg-white dark:bg-slate-850 p-2 rounded-xl border border-gray-100 dark:border-slate-800/50">
                  <p className="text-gray-400 font-sans uppercase">Sales Count</p>
                  <p className="text-indigo-600 text-xs mt-0.5">{totalExecutiveSalesSum} Unit(s)</p>
                </div>
              </div>
            </div>

            {/* Hovered Month Composition details */}
            <div className="bg-gray-50/25 dark:bg-slate-800/15 border border-gray-100 dark:border-slate-800/50 rounded-3xl p-5 flex-1 flex flex-col justify-between">
              {(() => {
                const targetKey = hoveredMonth || monthlyChartData[monthlyChartData.length - 1]?.monthKey;
                const activeMonthDetail = monthlyChartData.find(d => d.monthKey === targetKey);

                if (!activeMonthDetail) {
                  return (
                    <div className="flex-1 flex flex-col items-center justify-center text-center py-6">
                      <Activity className="w-8 h-8 text-gray-300 mb-2 animate-pulse" />
                      <p className="text-xs text-gray-400 font-semibold">Hover a bar to see composition details</p>
                    </div>
                  );
                }

                return (
                  <div className="space-y-4 flex flex-col justify-between h-full">
                    <div className="space-y-3">
                      <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800/80 pb-2.5">
                        <span className="text-[11px] font-bold text-gray-800 dark:text-slate-300 flex items-center gap-1.5">
                          <Layers className="w-3.5 h-3.5 text-indigo-505 text-indigo-550 text-indigo-550 text-indigo-550 text-indigo-500" />
                          Payout Composition
                        </span>
                        <span className="font-mono text-[10px] font-black text-gray-600 dark:text-slate-400 bg-gray-100 dark:bg-slate-800 px-2 py-0.5 rounded">
                          {activeMonthDetail.monthName}
                        </span>
                      </div>

                      {/* Detail List */}
                      <div className="space-y-2.5 text-xs">
                        {/* 1. Base Sequence Commission */}
                        <div className="flex items-center justify-between font-mono">
                          <span className="text-gray-550 text-gray-500 flex items-center gap-1.5">
                            <div className="w-2 h-2 bg-emerald-500 rounded-full" /> 
                            <span className="font-sans font-medium text-gray-600 dark:text-slate-300">Base Commission</span>
                          </span>
                          <span className="font-bold text-gray-800 dark:text-slate-200">
                            {activeMonthDetail.baseAmount.toLocaleString()} ৳
                          </span>
                        </div>

                        {/* 2. Floor Override Bonus */}
                        <div className="flex items-center justify-between font-mono">
                          <span className="text-gray-500 flex items-center gap-1.5">
                            <div className="w-2 h-2 bg-amber-400 rounded-full" /> 
                            <span className="font-sans font-medium text-gray-600 dark:text-slate-300">Floor Bonus overrides</span>
                          </span>
                          <span className="font-bold text-gray-800 dark:text-slate-200">
                            {activeMonthDetail.floorBonus.toLocaleString()} ৳
                          </span>
                        </div>

                        {/* 3. Executive Target Milestone Bonus */}
                        <div className="flex items-center justify-between font-mono">
                          <span className="text-gray-500 flex items-center gap-1.5">
                            <div className="w-2 h-2 bg-indigo-400 rounded-full" /> 
                            <span className="font-sans font-medium text-gray-600 dark:text-slate-300">Target Achievement</span>
                          </span>
                          <span className="font-bold text-gray-800 dark:text-slate-200">
                            {activeMonthDetail.targetBonus.toLocaleString()} ৳
                          </span>
                        </div>

                        {/* 4. Team Target Multi-bind Bounty */}
                        <div className="flex items-center justify-between font-mono">
                          <span className="text-gray-500 flex items-center gap-1.5">
                            <div className="w-2 h-2 bg-rose-400 rounded-full" /> 
                            <span className="font-sans font-medium text-gray-600 dark:text-slate-300">Team Target payout</span>
                          </span>
                          <span className="font-bold text-gray-800 dark:text-slate-200">
                            {activeMonthDetail.teamBonus.toLocaleString()} ৳
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Footer Aggregates Card */}
                    <div className="bg-white dark:bg-slate-900 border border-emerald-500/10 p-3.5 rounded-2xl flex items-center justify-between text-xs font-bold shadow-2xs mt-2">
                      <div className="space-y-0.5 shadow-3xs">
                        <span className="text-[9px] text-gray-400 uppercase font-sans">Aggregate Net Earning</span>
                        <p className="font-mono text-emerald-600 text-sm">{activeMonthDetail.totalIncentive.toLocaleString()} ৳</p>
                      </div>
                      <div className="text-right">
                        <span className="text-[9px] text-gray-400 uppercase font-sans">Vol</span>
                        <p className="font-mono text-gray-800 dark:text-slate-200">{activeMonthDetail.salesCount} sale(s)</p>
                      </div>
                    </div>
                  </div>
                );
              })()}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
